### ISSUE TITLE
Make “Enough time” accessibility feature more informative

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools#18]
Option:
"Enough time" 
Question:  can this be expanded to be more informative

**Comment by hidde** [comment]
Thanks for this feedback. 

We will have a place to explain all of these filters: [Selecting Authoring Tools page](https://wai-authoring-tools.netlify.com/authoring-tools/selecting#features). That does not mean that I'm opposed to having a more informative name. 

Would you have a suggestion? Ideally we keep word count super small.

**Comment by hidde** [comment]
Closing this issue, so that we can discuss it in the broader issue #47.
