### ISSUE TITLE
Details box: use full name for features

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools#24]
Accessibility features: (pse add a colon after features)

A lot of the bullet points have dashes in between the words.
Can these dashes be replaced with spaces?

**Comment by hidde** [comment]
This is for technical reasons, what we're displaying here is the technical “id”.

I will start using full names, and leave this issue open until I've addressed that.

**Comment by yatil** [comment]
+1

**Comment by hidde** [comment]
This was address in 815630b , closing the issue.
