### ISSUE TITLE
Provide more realistic data

### ISSUE THREAD

**Issue by hidde** [w3c/wai-authoring-tools#27]
* For the “Stripmetics” tool entry, please add all 23 of the accessibility features in the details area, along with several comments. So we can see how long it could actually be.
* For the “Setuphub” tool entry, please list only two accessibility features in the details area.
* For the “Currce” tool entry, please list around 10-12 accessibility features to the details area.

**Comment by slhenry** [comment]
Thanks, Hidde. This helps!

One thing missing in the second and third listing:  the "Not supported or applicable: " list is incomplete.

**Comment by slhenry** [comment]
I was hoping you could easily add it in the non-working prototype. If it takes less then 20 minutes or so, please do.

**Comment by hidde** [comment]
It takes much more than 20 minutes. Closing this issue, this will automatically be fixed when there is real data.
