### ISSUE TITLE
Including data existing ATAG criteria

### ISSUE THREAD

**Issue by hidde** [w3c/wai-authoring-tools#3]
During EO WG review of the [Requirements Analysis: Authoring Tools List · w3c/wai-authoring-tools Wiki](https://github.com/w3c/wai-authoring-tools/wiki/Requirements-Analysis:-Authoring-Tools-List), we discussed whether we should have only vetting questions that are directly in ATAG, or also others.

**Comment by hidde** [comment]
Suggestions from EO WG meeting:

* Does authoring tool use AI to attempt fixing accessibility barriers?
* Is this authoring tool free or paid?

**Comment by hidde** [comment]
In the [2 August EO call](https://www.w3.org/2019/08/02-eo-minutes.html) @slhenry  said: 

> I think we should add feel free to add these kinds of questions (outside ATAG) as vetting questions 

I agree and would propose we add any questions we find relevant. 

I'd say the criterion for a question should be ”we expect it will be helpful for users as a filter for authoring tools”.

**Comment by eoncins** [comment]
One of the problems raised in the meeting regarding the vetting questions was the need for a review. If a review is provided to a vetting question then I agree.

**Comment by slhenry** [comment]
/me suggests changing "vetting" in this title.

Vetting to me means we will evaluate the statements, and I don't think we will.

I think it's:
"Including data beyond existing ATAG criteria"

**Comment by hidde** [comment]
You are right, we definitely will not evaluate the statements. Have changed to “self-vetting” to clarify.

**Comment by hidde** [comment]
Updated title to @slhenry 's suggestion.

Free/paid is now part of the tool, so is 'has public accessibility statement'.

**Comment by hidde** [comment]
I'll close this now, as the initial concerns are addressed.
