### ISSUE TITLE
Title full width

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-authoring-tools#32]
Please let the title take up the full width.

For me, it's breaking into two lines, even though there is plenty of space for it to continue on the same line.

While there is merit to making blocks of text (that is, paragraphs of multiple sentences) shorter line length, that doesn't apply to a stand-alone title. It is awkward and takes more cognitive processing when it breaks unnecessarily.

**Comment by yatil** [comment]
From what I see from the code, the header uses the full width of the page (until the right edge of the content boxes). Putting the header outside of the main element would mean recoding the page templates. FWIW, I had a really hard time to make it break into two lines with “standard” text sizes. Only on mobile despite having “Draft” take up additional space.

**Comment by slhenry** [comment]
fixed https://github.com/w3c/wai-authoring-tools/issues/22#issuecomment-542178159 :-)
