### ISSUE TITLE
Filtered out clarification

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-authoring-tools#35]
Some usability studies we did a long time ago on previous iterations of the WCAG QuickRef showed that we need to make it **very** clear when/that/what [SCs/tools] are filtered out -- especially when printed.

Please see what's done in the [Eval Tools List](https://www.w3.org/WAI/ER/tools/?q=wcag-20-w3c-web-content-accessibility-guidelines-20) and [QuickRef](https://www.w3.org/WAI/WCAG21/quickref/)
&mdash; and provide options on what we might want to do differently for this new template.

e.g., for this Authoring Tools list and for the Eval Tools list, I'm wondering if:
* at the top, can just say "Showing X of Y authoring tools." and don't need more details
* in print version, can have the filter criteria just at the bottom

(Note: These are different from the WCAG Quick Ref list. For the QuickRef, I think it's vital to have at the top the "Selected Filters" details and "(What did the filter remove?)" link at the top and list at the bottom. Unless convinced otherwise, I don't think that's important for the Tools lists.)

**Comment by hidde** [comment]
> at the top, can just say "Showing X of Y authoring tools." and don't need more details 

In this, would X be all tools in the current selection and Y all tools that are available in total?

I prefer how it currently is, displaying just the total of tools currently displayed. Less cognitive load.

> in print version, can have the filter criteria just at the bottom

In theory, yes, we can have that, given that there is time to build and test. I'll have create a separate issue for that (#60) so that we can plan for it separately.

**Comment by hidde** [comment]
See also #46

**Comment by hidde** [comment]
The print issue is being addressed in #60. 

The ensuring that we have “Showing X out of Y” is happening in #66 . 

That leaves us with no work left for this issue, so I am closing this.
