### ISSUE TITLE
Type of Tool – Radiobuttons?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#36]
I wonder if there is a good use case for searching for (for example) Content Management Systems and Wikis. (I assume that would show CMS and wikis, not tools tagged with both, CMS AND wiki.)

**Comment by hidde** [comment]
Now that you say it, I think it is an unlikely use case.

On the other hand, is there harm in leaving open the possibility?

**Comment by yatil** [comment]
No harm.
