### ISSUE TITLE
Make filters easier to scan

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#37]
<img width="335" alt="Screen Shot 2019-10-16 at 08 15 07" src="https://user-images.githubusercontent.com/58862/66892899-21828400-efed-11e9-897e-95cc300c37f9.png">

Especially with filter criteria that has two lines, it feels hard to scan. I’d suggest to add some spacing to the filters or add some light borders between the options to guide the eye:

<img width="335" alt="Screen Shot 2019-10-16 at 08 17 22" src="https://user-images.githubusercontent.com/58862/66893046-73c3a500-efed-11e9-929f-06759fd749ea.png">

**Comment by hidde** [comment]
I have tried a few different things including a subtle border in between, but have landed on this solution: double the amount of spacing in between, which looks similar (the same?) as in your last screenshot.

Feel free to reopen if you feel it is not quite right yet.

<img width="306" alt="List of accessibility features with spacing in between" src="https://user-images.githubusercontent.com/178782/67296256-81df5d00-f4e8-11e9-8e88-26857081ce41.png">

**Comment by yatil** [comment]
Looks good!
