### ISSUE TITLE
Make Expand/Collapse buttons consistent with other WAI properties

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#38]
- [x] We usually have a + in buttons that open something and a &minus; in buttons that close something. – Editor’s discretion, but I think it would be nice to have consistency :-)
- [x] The button does not stay “pressed” visually when the expand/collapse is opened and the focus moves away. This should just be a `details[open] summary { }` CSS styling away from being fixed.

I think we should standardize buttons in summaries for detail elements for the whole site eventually, because I like how it looks & works.

**Comment by hidde** [comment]
I totally agree, just fixed. (The difference between mine and the others was that my `<summary>` did not contain children, just text. So there nothing to attach the +/- to.)

Arguably, it now looks more beautiful, and more in line with rest of WAI site.

![screenshot of header with plus and minus sign](https://user-images.githubusercontent.com/178782/68873783-6be84500-0700-11ea-847b-60a0ad34b8ed.png)

cc @slhenry
