### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#39]
Editor’s suggestion: On mobile when opening it, I only see the intro/disclaimer and the top of the filtering list. Might be good if both was expandable or having a link to the tools. 

- [x] The spacing of and around certain items needs some more polish in certain areas (Button spacing).
- [x] The tool info should be one column on small screens: <img width="335" alt="Screen shot of two columns, making each column very small" src="https://user-images.githubusercontent.com/58862/66894957-0108f880-eff2-11e9-92fd-b0357130e072.png">

**Comment by hidde** [comment]
I have updated the tool info to display as one column, and become two columns only when viewport is wider than `30em` .

**Comment by hidde** [comment]
For spacing around items, I have assumed that this is mostly about the spacing between Filter button and tools list. I [addressed this in issue 41](https://github.com/w3c/wai-authoring-tools/issues/41#issuecomment-545342150).

Will open a separate issue for expandable/linking to tools on small screens, I think it is very valid, but not sure how to solve it best yet (I think we may want to open filters from some sort of non-modal sidebar, even).
