### ISSUE TITLE
Accessibility Features  suggestions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#40]
Summary:

- ~Visually indicate that 'Not supported' is part of accessibility features and that those two are separate from the 'meta' info (including license, cost model, etc)~ to be continued in #49)
- [x] Clearly mark vendor comments
 ~Open more info about accessibility features in new tab~ (fixed in https://github.com/w3c/wai-authoring-tools/issues/31#issuecomment-553924879)

I think the “Accessibility Features” can be tightened up somewhat.

Currently it looks like this:

<img width="810" alt="Accessibility Features view as Oct 16" src="https://user-images.githubusercontent.com/58862/66895264-a328e080-eff2-11e9-808f-b8b16fd474be.png">

The “not supported” text looks like it belongs to the next section somehow, so changing the margins there should help. I could even see a border between the two sections to make it really clear. 

It is also too small. (Probably a bug with our `<small>` element.) I think knowing what the tool does not support is as important as what the tool does support, therefore I think it should be listed equivalently. 

I think we need to clearer mark the vendor comments, otherwise people will mistake it for our own content.

Last, but not least, I think we can move the “more info about accessibility features” to the top. Can I suggest opening it in a new window/tab (I guess the state the tool is in is preserved when navigating back and forth, but not every user will have that assumption.)

So, something like this? (Obviously very rough.)

<img width="810" alt="Doctored website screen shot" src="https://user-images.githubusercontent.com/58862/66896463-20edeb80-eff5-11e9-9f25-6b23aad6dee7.png">

For the accessibility features, I wonder if we want to have icons there: Checked for ”has it”, minus for “partial” and X for “hasn't it”. Together with having the features in the same order under every tool, it would also facilitate scanning.

**Comment by hidde** [comment]
I have added a checklist to the top with part of the issues. I left this out:

> move the “more info about accessibility features” to the top.

What about making 'Accessibility Features' a link here (that opens in new window)? 

Also related to https://github.com/w3c/wai-authoring-tools/issues/49

> The “not supported” text looks like it belongs to the next section somehow, so changing the margins there should help. I could even see a border between the two sections to make it really clear.
>
> It is also too small. (Probably a bug with our <small> element.) I think knowing what the tool does not support is as important as what the tool does support, therefore I think it should be listed equivalently.

This means each listing will have 23 features, and especially if many of them have comments (which is likely as we expect a lot of partial support). 

I'm usually not the person to throw a suggestion for tabs in, but… I wonder if we should have two tabs here: one for supported, one for not supported? That's equal display of information, while taking up less space.

**Comment by yatil** [comment]
> What about making 'Accessibility Features' a link here (that opens in new window)?

Would be ok for me.

> This means each listing will have 23 features, and especially if many of them have comments (which is likely as we expect a lot of partial support).

Good considerations… 23 seems a lot with comments. I could see making the comments expand/collapse, but that would introduce more complexity., so I guess your initial suggestion on how to handle it is fine, really.

(Not a big fan of tabs if we can avoid it. )

**Comment by hidde** [comment]
Update: “Accessibility features” is now the info icon as discussed in https://github.com/w3c/wai-authoring-tools/issues/31#issuecomment-553924879.  Have removed from checklist above.

**Comment by hidde** [comment]
Closing this issue: what remains is how to organise the 23 criteria, and we're leaning towards tabs  in #49. Continuing that part of this issue there. Thanks for the comments here!
