### ISSUE TITLE
in Details, group list items into 2

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-authoring-tools#42]
I think it would be better usability to group the list items into 2 like the filters:

Accessibility for content editors (editing experience)
* ...
* ...

Accessibility for end users (output)
* ...
* ...

or, maybe a shortened version, e.g., 
For content editors
For end users
_or_
Editing experience
Output

**Comment by hidde** [comment]
Good point! Especially if the list is as long as having all the features.

I can't make my mind up between talking about users ('for content editors'/'for end users') or what the features affect ('editing experience'/'output'), and am tempted to have both. 

Do you have a preference?

**Comment by eoncins** [comment]
+1 to Slhenry suggestion for group list depending on type of user.

**Comment by hidde** [comment]
I have restructured the data to allow for this feature request and displayed the data as requested.

It now looks like this:

<img width="415" alt="two lists of features with a heading above each" src="https://user-images.githubusercontent.com/178782/67268305-5f335100-f4b4-11e9-9011-5b3832fb86ac.png">

It is a lot of bold, will make it less bold while keeping the visual hierarchy / scannability.

**Comment by hidde** [comment]
Have unbolded feature names. To still have some difference between description and feature name, I have made comments display in italics.

<img width="480" alt="heading with two features, each displayed in regular font weight with description in italics" src="https://user-images.githubusercontent.com/178782/67268601-2778d900-f4b5-11e9-8bf3-74fb2e15d159.png">
