### ISSUE TITLE
Focus styling

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#44]
For editors discretion, also this might have much broader implications.

The focus indicator is generally a dark blue outline. I wonder if a more visually salient colour could be used. Gov.uk have a gold outline for focus styling on form elements, and a full block for links. This makes the elements much more visually salient.

I appreciate that this might impact on other resources, but if this is to set patterns it might be worth considering.

**Comment by hidde** [comment]
Hi Kevin, thanks for this feedback! I've re-filed this issue in https://github.com/w3c/wai-website/issues/200, because, as you say, it has broader implications: the Authoring Tools List does not define a focus style, but inherits it from the WAI styling, changing it would need to happen there.

**Comment by yatil** [comment]
The current design was agreed during the redesign process. It uses currentColor to ensure 7:1 contrast in most situations. We also have an animation of the outline. The feedback from keyboard and low vision users has been positive so far, I don’t see an urgent reason to re-evaluate this decision.
