### ISSUE TITLE
Indicate total number of tools

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#46]
Related to #45, the total number of tools in the library is not indicated.

**Comment by hidde** [comment]
It is indicated, at the top it says “Showing 9 tools”, where 9 is the total number: 

Screenshot: 

<img width="279" alt="Showing 9 tools" src="https://user-images.githubusercontent.com/178782/67369479-5eb0be00-f579-11e9-8828-a2532aeeb065.png">

Once more filters are selected, that number will not be the total number, but i think that is what people would expect?

**Comment by slhenry** [comment]
I would expect that when filters are applied, it would say: " Showing X of X tools."

If that is the case, then I think we're all good. ;-)

**Comment by hidde** [comment]
It is not currently showing that, but I'll take your comment and Kevin's thumbs up as the group's inclination towards this and have created a task for myself to implement this.

Have opened task #66 for myself and added to To Do, closing this issue now.
