### ISSUE TITLE
Styling of tool name and vendor suggest that they are links

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#48]
Taking more time to look at them it is clear that they are not. However, while I was working through I clicked on the tool name thinking I would access more information about that tool specifically or (as in Evaluation Tools List) it would go to the tool home page.

**Comment by hidde** [comment]
Thanks, Kevin.

I wonder if it makes sense to remove the 'Website' entry under 'Details', and just make the name of the tool a link to the website of the tool.

That would reduce the amount of info to digest in 'Details' , while also making the tool name work as you (and I suspect many users) would expect.

**Comment by iadawn** [comment]
I think I would agree.

**Comment by hidde** [comment]
Adding it to my to do list!

**Comment by hidde** [comment]
This has been addressed in 7353b19. 

Note, not all tools have a website (in my made up data, anyway), so I have underlined those that do. This means for some tools, the name is a link and underlined, for some tools it is not. 

Closing this issue for now, please do feel free to reopen if you feel the solution I've provided is suboptimal.
