### ISSUE TITLE
How can we let people give feedback on tool submissions?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-authoring-tools#5]
Authoring tool submissions can be submitted by anyone, and the submitter will answer the vetting questions.

I anticipate that in some cases, people disagree about how one or more vetting questions are answered. For example, submitter may say “My CMS is perfectly usable with keyboard only”, someone else might know that the sidebar really requires a mouse. 

We want to welcome this kind of feedback and facilitate discussion.

We probably want this: 

* public
* easy to chime in
* reinforce the idea that this is a community resource

**Comment by hidde** [comment]
After the [discussion on 2 August](https://www.w3.org/2019/08/02-eo-minutes.html) my suggestion would be that each listing has a link to report, which simply links to [issues/new](https://github.com/w3c/wai-authoring-tools/issues/new) in this repo, where we supply an [issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) for reporting a problem with an authoring tool.

So it would be something like: 

[Is there something wrong?](https://github.com/w3c/wai-authoring-tools/issues/new)

**Comment by eoncins** [comment]
+1 to use an issue template for reporting a problem with an authoring tool.
One of the issues raised in the meeting was the need for feedback in these cases. In the case that an issue is reported then a feedback will be needed.

**Comment by hidde** [comment]
This functionality has been taken out of the site for the first version, as we have no process in place to process feedback, and will for now deal with it on a case by case basis.
