### ISSUE TITLE
Summary and description needed?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#50]
When submitting a tool, a description can be added. This (I am assuming) is then used when displaying the list of tools. It is highly likely that vendors will not confine themselves to a couple of lines to describe their tool.

I would suggest including a summary and a description field. The summary encourages vendors to provide limited information, or even imposes a character limit. The summary is used to display on the tools list.

The description provides much more open text and allows for extensive content. This is then displayed when the tool details are revealed.

**Comment by hidde** [comment]
I like the idea of imposing a character limit, it would level the playing field and give each tool the same opportunities.

I wonder if a full description is needed though? Alternatively, the tool's own website can serve as a full description for our character-limited summary?

**Comment by yatil** [comment]
I would just use one character-limited field. If we have a longer field, people will abuse it with marketing/keyword stuffing and it also means it is much harder to review.

**Comment by slhenry** [comment]
Also, in the Submit a Tool, provide good guidance to help them provide a good, clear, descriptive description (and avoid market-eze!).

**Comment by hidde** [comment]
This was discussed at EOWG today, the group leaned towards having a summary field only and adding a character limit.

**Comment by hidde** [comment]
Opened task #59 to address this issue, closing this discussion for now.
