### ISSUE TITLE
Non-text Contrast

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#51]
Form element focus styling includes a pale blue block border around the element. The contrast between this and the background colour is 1.1:1, which is below 3:1.

Does this need to be higher?

**Comment by hidde** [comment]
I suppose it does, thanks for verifying this contrast. These styles are WAI website wide, so if we address it it will be everywhere.

Looping in @yatil and @slhenry: should we update focus in our WAI form styles? (if yes, should I close this issue and open one in wai-website-theme?

**Comment by yatil** [comment]
Yes. We never had a design for forms and everything we have right now is improvised/browser default. Every addition is very welcome from my side.

**Comment by hidde** [comment]
Thanks for the context, @yatil. In that case I can propose some tweaks to address @iadawn's comment. Adding this to the 'Backlog'.

**Comment by hidde** [comment]
Have filed this in https://github.com/yatil/wai-website-theme/issues/5, closing the issue in this repository, as it is outside of this website's scope.
