### ISSUE TITLE
400% zoom details labels too broad

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools#56]
The space allocated for the details label seems to be more than the content. This is forcing the content to be more squashed than is necessary.

![image](https://user-images.githubusercontent.com/2444840/67084706-5fbaa780-f195-11e9-8ba9-678118c2eac3.png)

**Comment by hidde** [comment]
Thanks for filing this. 

I am happy to report that I've been able to address this in https://github.com/w3c/wai-authoring-tools/commit/058580b6f53f6ec4b36c11c183405736f8b25d21. Solution is to stack this information, which key and value (e.g. “License” and “MIT”) each on their own line.
