### ISSUE TITLE
[minor] Add (editing experience) and (output) to detailed view

### ISSUE THREAD

**Issue by yatil** [w3c/wai-authoring-tools#64]
Currently the headings are _“Features for content editors”_ and _“Features for end users”_.

In the filter bar on the left, it says _“Accessibility for content editors (editing experience)”_ and _“Accessibility for end users (output)”_.

I think it would be good to wither use the same language in both places (Features for *), I would also encourage to front-load the headings: “Content Editors’ Features (editing experience)” and “End User Features (output)”.

**Comment by hidde** [comment]
Thanks, that's a great idea, consistency and front loading should aid usability here. Have addressed

**Comment by yatil** [comment]
Thanks, Hidde!
